repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
      exclude: ^third_party/
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  # - repo: https://github.com/jumanjihouse/pre-commit-hooks
  #   rev: 2.1.5
  #   hooks:
  #     - id: markdownlint
  #       args: ["-r", "~MD002,~MD013,~MD024,~MD029,~MD033,~MD034,~MD036", "-t", "allow_different_nesting"]
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "79"]
